name: Otomatisasi Pengujian ESP32 MPU6050

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-wokwi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Wokwi CI Test
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: .
          configPath: 'sensor_MPU5060_test.yaml'